In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('All_Data.csv')
df.head()

,Unnamed: 0,Timestamp,Score,ID,Gender,Height,Weight,CGPA,Daily spent time in social media (hour),Hometown,...,Place Name,Latitude,Longitude,Place Name2,Latitude2,Longitude2,Food you like most,Leisure time activity,Future plan,Typically your days are started at:
0,0,3/29/2019 0:23:23,0 / 1,121440946,Male,5 ft 10 inch,90,2.34,Below 1 hour,Comilla,...,Mirpur,23.838115,90.364520,New York,40.712776,-74.005974,Nothing Specific,Listening songs,Higher Study,07:00:00
1,1,3/29/2019 3:00:10,0 / 1,131440910,Female,"5'3""",42,2.50,2019-05-02 00:00:00,Bogra,...,Modhubag,23.757242,90.412399,Paris,48.856613,2.352222,Pizza,sketch,Graphic Design,09:00:00
2,2,3/28/2019 23:40:52,0 / 1,131440969,Male,5.4,60,2.80,2019-05-02 00:00:00,Narsinghdi,...,Niketan Bazar,28.350180,77.287740,Niagara Falls,43.082817,-79.074165,Biriyani,Watching Movie,Higher Study,10:00:00
3,3,3/28/2019 23:17:47,0 / 1,141340900,Male,5'8'',70,2.47,Above 5 hour,Rajshahi,...,modhubag,23.757243,90.412399,New York,40.712776,-74.005974,Kacchi,Watching cricket,Any job,08:00:00
4,4,3/24/2019 15:31:24,0 / 1,141440899,Female,156cm,76,3.62,2019-05-02 00:00:00,Chittagong,...,Mohakhali DOHS,23.782860,90.395439,Canada,56.130367,-106.346771,Pasta,Rading Books,Higher Study,10:00:00

In [5]:
import nltk
nltk.edit_distance("Yes", "Yes i will")

7

In [6]:
for c in df.columns:
    print(c)

Unnamed: 0
Timestamp
Score
ID
Gender
Height
Weight
CGPA
Daily spent time in social media (hour)
Hometown
How many days in a week you feel more energetic
Favorite transport mode
Favorite food names
Expected food price of that favorite food
Month cost for that particular food
What do you like home delivery or eat in the restaurant
University travel cost monthly
Hobby
Travel package you prefer
Sickness-frequency in a month
Favorite food in summer/winter/rainy season
Food flavor
Hangout location(Spend most of the time)
Typically you go out with
Travel budget
favourite restaurant
Unnamed: 25
Restaurant location
Live with family(y/n)
Are you happy with current situation?
Number of programming hours spent per day
Sleep duration
Do you start your day by planning(y/n)
Do you have online shopping experience (y/n)
Do you use products for grooming(y/n)
Favourite food in rainy season
Prefers(food_quality/environment)
No of time home delivery over a month(Number)
No of time goes to restaurant over a month( n umber)
Pickup location of yours for bus
Pickup time of yours for bus
Your bank name
Preferred shopping area
Monthly frequencies of shopping
Do you prefer to play in Gaming Zone ?
Are you fashion active
Which colour do you prefer(red/yellow)?
Which cloths do you choose to wear(urban/linen shirt and trousers/jeans&shirt)?
Do you feel low seeing other people's achievement on social media
Recently how many of your family members/neighbours affected by dengue
do you find bargaining pleasing?
Actual motive behind your future goal?
Would you still pursue your goal if the motive behind it is fulfilled in another way?
Do you think it is a good idea to go to a well known shop just for the sake of social status?why?
How much do you earn monthly?
Wake up time?
When is your class starting time
When is your class ending time
What do you love most?
Are you satisfied with your countryâ€™s law?
Which law do you prefer more?
Whatâ€™s your view about law enforcement groups?
Are you eager to harm yourself to defend your beliefs?
How frequently you visit a doctor within a year"
How many people do you follow on social media?
How much time you spend in university without academic curriculum(in hour)?
Are you rich in vocabulary?
Class note taking tendency(High,Low,Medium)
Theory class attendance(h,l,m)
Theory class interest(h,l,m)
Lab interest(h,l,m)
Preference(class lectures cl or online tutorials)
Place Name
Latitude
Longitude
Place Name2
Latitude2
Longitude2
Food you like most
Leisure time activity
Future plan
Typically your days are started at:

In [7]:
table = pd.pivot_table(df, values='ID', index=['Future plan','Would you still pursue your goal if the motive behind it is fulfilled in another way?'], aggfunc='count')
table

                                                                                      ID
Future plan                       Would you still pursue your goal if the motive ...
Aerospace Engineer                Yes                                                  1
Afflulent                         Yes                                                  1
Ai Architecture                   yes                                                  1
Any job                           yes                                                  1
BCS                               No                                                   1
                                  No.                                                  1
                                  Yes                                                  2
                                  may be                                               1
                                  yes                                                  1
BCS/Business                      May be                                               1
CEO                               no                                                   1
Data Scientist                    Maybe                                                1
                                  yes                                                  1
Database Analyst                  Yes                                                  2
Don't have                        Depends.                                             1
                                  May be                                               1
                                  Maybe                                                1
                                  No                                                   4
                                  maybe                                                1
                                  no                                                   1
                                  yes                                                  1
Entrepreneur                      Probably                                             1
                                  YES                                                  1
                                  yes                                                  1
Full Stack Developer              No                                                   1
                                  Yes                                                  1
Game Developer                    yes                                                  1
Game Development                  Yes                                                  1
                                  yes                                                  1
Graphic Design                    yes                                                  1
...                                                                                   ..
Network Specialist                Yes                                                  1
Not decided yet                   no                                                   1
PhD                               Yes                                                  1
S/w enginner                      No                                                   1
Software Developer                Maybe                                                1
                                  NO                                                   1
                                  Yes                                                  4
                                  yes                                                  4
                                  yes I will                                           1
Software Engineer                 No                                                   1
                                  Yes                                                  1
                                  maybe                                                1
Teacher                           yes                                                  1
Teaching                          No                                                   1
                                  no                                                   1
                                  yes                                                  1
To get a good job                 maybe                                                1
Traveling                         Yes                                                  1
Travelling                        Yes                                                  1
                                  yes                                                  1
Web Developer                     Yes                                                  1
Web Development                   Yes                                                  1
Web developer                     yes                                                  1
Working on Machine Learning Field Yes                                                  1
bcs                               no                                                   1
businessman                       yes                                                  1
give own IT Farm                  yes, I would                                         1
job                               no                                                   1
software Engineer                 no                                                   1
still in progress                 Yes                                                  1

[72 rows x 1 columns]